package genetica.apresentacao;

import genetica.natureza.Individuo;
import genetica.natureza.Populacao;
import genetica.roleta.ControleRoleta;
import genetica.roleta.ObservadorRoleta;
import genetica.suporte.Log;
import genetica.suporte.ObservadorLog;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author marano
 */
public class Monitor extends javax.swing.JFrame implements ObservadorRoleta, ObservadorLog {

    private ControleRoleta controle;
    private TabelaModelo<Individuo> modeloTabelaPopulacao;

    public Monitor(ControleRoleta controle) {
        initComponents();
        exibir();

        this.controle = controle;
        controle.adicionarObservedor(this);
        carregarDadosControleRoleta();

        carregarTabelaPopulacao();
        lblModelo.setIcon(new ImageIcon(this.getClass().getResource("img/animacao_dna.gif")));

        btnParar.setEnabled(false);
        barraProgresso.setStringPainted(true);

        adicionarListeners();

        spnItervalo.setValue(new Integer(100));

        txtLog.setText(Log.getTexto());
        Log.setObservador(this);
    }

    public void logAtualizado(String textoNovo) {
        txtLog.append(textoNovo);
        scrollLog.getViewport().setViewPosition(new Point(0, txtLog.getHeight() - scrollLog.getHeight()));
    }

    private void adicionarListeners() {
        btnExecutar.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                controle.setTamanhoPopulacao((Integer) spnTamanhoPopulacao.getValue());
                controle.setTotalIteracoes((Integer) spnQuantidadeIteracao.getValue());
                controle.executar();
            }
        });
        btnParar.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                controle.parar();
            }
        });
        chkLog.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                Log.setLogAtivado(chkLog.isSelected());
            }
        });
    }

    private void carregarDadosControleRoleta() {
        spnTamanhoPopulacao.setValue(controle.getTamanhoPopulacao());
        spnQuantidadeIteracao.setValue(controle.getQuantidadeIteracao());
    }

    public void roletaRodou(int iteracaoAtual, int totalIteracoes) {
        barraProgresso.setMaximum(totalIteracoes);
        barraProgresso.setValue(iteracaoAtual);
        try {
            Thread.sleep((Integer) spnItervalo.getValue());
        } catch (InterruptedException ex) {
            ex.printStackTrace();
        }
    }

    public void populacaoAlterada(Populacao populacao) {
        modeloTabelaPopulacao.setObjetos(populacao.getIndividuos());
        lblTotalAptidao.setText(Integer.toString(populacao.totalAptidao()));
    }

    public void inicioIteracoes() {
        btnExecutar.setEnabled(false);
        btnParar.setEnabled(true);
    }

    public void fimIteracoes() {
        btnExecutar.setEnabled(true);
        btnExecutar.setText("Reiniciar");
        btnParar.setEnabled(false);
    }

    private void carregarTabelaPopulacao() {
        modeloTabelaPopulacao = new TabelaModelo<Individuo>(tblPopulacao,
                new String[]{"Indivíduo", "Valor", "Aptidão"}) {

            @Override
            public Object getValor(Individuo objeto, int indiceColuna) {
                switch (indiceColuna) {
                    case 0:
                        return objeto.getGenesString();
                    case 1:
                        return objeto.getValor();
                    case 2:
                        return objeto.aptidao();
                    default:
                        throw new RuntimeException("Não foi possível definir o campo do indivíduo!");
                }
            }
        };
        tblPopulacao.setDefaultRenderer(Object.class, new RenderizadorCelulaCentralizada());
    }

    private void exibir() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnTamanhoPopulacao = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnQuantidadeIteracao = new javax.swing.JSpinner();
        btnExecutar = new javax.swing.JButton();
        barraProgresso = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        spnItervalo = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        btnParar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPopulacao = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotalAptidao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        scrollLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lblModelo = new javax.swing.JLabel();
        chkLog = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Genetic Calculator Tabajara");

        jLabel1.setText("População");

        jLabel2.setText("Iterações");

        btnExecutar.setText("Iniciar");

        jLabel4.setText("Intervalo");

        jLabel6.setText("ms");

        btnParar.setText("Parar");

        jScrollPane1.setViewportView(tblPopulacao);

        jLabel3.setText("Total Aptidão");

        lblTotalAptidao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalAptidao.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalAptidao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalAptidao)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("População", jPanel1);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        scrollLog.setViewportView(txtLog);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollLog, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollLog, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Log", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visualizar Modelo 3D", jPanel3);

        chkLog.setText("Log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnTamanhoPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQuantidadeIteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnItervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)
                        .addGap(40, 40, 40)
                        .addComponent(chkLog))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barraProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnTamanhoPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spnQuantidadeIteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnItervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(chkLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExecutar)
                        .addComponent(btnParar))
                    .addComponent(barraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JButton btnExecutar;
    private javax.swing.JButton btnParar;
    private javax.swing.JCheckBox chkLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblTotalAptidao;
    private javax.swing.JScrollPane scrollLog;
    private javax.swing.JSpinner spnItervalo;
    private javax.swing.JSpinner spnQuantidadeIteracao;
    private javax.swing.JSpinner spnTamanhoPopulacao;
    private javax.swing.JTable tblPopulacao;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
