/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaLogo.java
 *
 * Created on 30/03/2009, 03:24:47
 */
package genetica.apresentacao;

import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author marano
 */
public class TelaLogo extends javax.swing.JFrame {

    private boolean continuar = false;

    /** Creates new form TelaLogo */
    public TelaLogo() {
        carregarTela();
        carregarListeners();
        carregarThreadTimeout();
        esperar();
        dispose();
    }

    private void carregarListeners() {
        addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                continuar = true;
            }
        });
        addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
                continuar = true;
            }
        });
    }

    private void carregarTela() {
        initComponents();
        lblImagem.setIcon(new ImageIcon(this.getClass().getResource("img/calculator_logo.jpg")));
        setPreferredSize(new Dimension(399, 450));
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void carregarThreadTimeout() {
        new Thread(new Runnable() {

            public void run() {
                try {
                    barraCarregamento.setMaximum(8);
                    barraCarregamento.setValue(0);
                    barraCarregamento.setString("carregando ...");
                    barraCarregamento.setStringPainted(true);
                    Thread.sleep(1000);
                    barraCarregamento.setValue(1);
                    barraCarregamento.setString("carregando ácido desoxirribonucleico ...");
                    Thread.sleep(1000);
                    barraCarregamento.setValue(2);
                    barraCarregamento.setString("carregando equações trigonométricas ...");
                    Thread.sleep(1000);
                    barraCarregamento.setValue(3);
                    barraCarregamento.setString("carregando 827346273 proteínas conhecidas ...");
                    Thread.sleep(1000);
                    barraCarregamento.setValue(4);
                    barraCarregamento.setString("carregando combinações polinucleicas ...");
                    Thread.sleep(1000);
                    barraCarregamento.setValue(5);
                    barraCarregamento.setString("carregando modelos tridimensionais do DNA ...");
                    Thread.sleep(1000);
                    barraCarregamento.setValue(6);
                    barraCarregamento.setString("carregando som 5.1 ...");
                    Thread.sleep(1000);
                    barraCarregamento.setValue(7);
                    barraCarregamento.setString("carregando novas regras de acentuação ...");
                    Thread.sleep(1000);
                    barraCarregamento.setValue(8);
                    barraCarregamento.setString("concluído!");
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                }
                continuar = true;
            }
        }).start();
    }

    private void esperar() {
        try {
            while (!continuar) {
                Thread.sleep(50);
            }
        } catch (InterruptedException ex) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barraCarregamento = new javax.swing.JProgressBar();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("carregando...");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(254, 254, 254));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        barraCarregamento.setBorder(null);

        lblImagem.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barraCarregamento, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblImagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraCarregamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraCarregamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem;
    // End of variables declaration//GEN-END:variables
}
